### ISSUE TITLE
not testing and running correctly on linux (ubuntu 12.04 particularly)

### ISSUE THREAD

**Issue by thnguyen** [livinginthepast/fake_ftp#23]
We used fake_ftp for our testing and it's rspec tests are failing all over and not running correctly on our environment (ubuntu 12.04 rbenv ruby 2.0.0-p247). I have developed a fix and like to contribute back to the project

**Comment by mgates** [comment]
@thnguyen Can you share you solution? I'm running into the same problem.

**Comment by meatballhat** [comment]
We're no longer testing this against Ubuntu 12.04 given it's EOL.  Please holler if you're still hitting issues, especially on other distros/versions :heart:

**Comment by erbunao** [comment]
@meatballhat @thnguyen Unfortunately I'm still experiencing the same issue when running multiple tests. I installed the version 0.2.0 for ruby version compatibility issue.
